version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: postcss
    versions:
    - 8.2.2
    - 8.2.4
  - dependency-name: meow
    versions:
    - 8.1.0
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: known-css-properties
    versions:
    - 0.20.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: globby
    versions:
    - 11.0.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
